### ISSUE TITLE
Test #1

### ISSUE THREAD

**Issue by hobertro** [teresa210/cs-team#1]
- Find a way to center the cs team page
- Hint: https://www.freecodecamp.org/news/how-to-center-things-with-style-in-css-dc87b7542689/
- Try out each method
- Example: 

<img width="1397" alt="Screen Shot 2020-04-18 at 3 17 27 PM" src="https://user-images.githubusercontent.com/2173819/79672521-bbd3a800-8187-11ea-8543-75beb56f6447.png">

**Comment by teresa210** [comment]
![image](https://user-images.githubusercontent.com/13227292/79678276-74144700-81ae-11ea-84b5-945d829e6745.png)

**Comment by hobertro** [comment]
nicework TT
